# Generated by Django 3.1.5 on 2021-01-07 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='descrioption',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='items',
            name='price',
        ),
    ]
