# Generated by Django 3.1.5 on 2021-01-07 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20210107_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='article_body',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
